apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  gitdata-ai
  annotations:
    meta.helm.sh/release-name: gitdata-ai
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    apptype: gitdata-ai
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release:  gitdata-ai
spec:
  ingressClassName: {{.Values.ingress_name}}
  rules:
    - host: gitdata.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitdata-ai-service
                port:
                  number: 80
